language: android
android:
  components:
    - platform-tools
    - build-tools-21.1.1
    - android-21
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support

script:
   - ./gradlew build connectedCheck --stacktrace

before_install:
 - chmod +x gradlew